title: Starter.dev
author:
  name: Phi
  email: phi@illumiphi.com
taxonomies:
  - category
  - tag
metadata:
  description: 'illumiphi - the architecture of you'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
